### PR TITLE
Allow disabling of boolean flags

### LINKED ISSUE #17: Should be able to do --lint=false to turn off lint
#### Describe the desired behavior
pxb new --lint=false should not install any lint & prettier

#### Describe the current behavior
As long as you have a --lint flag, lint will be installed; otherwise, it won't.

#### Is this request related to a current issue?
May want to do this while working on #16 .

#### Additional Context
This is an issue after #15 is merged

### PR DESCRIPTION
**Pull request by joebochill**
Changes proposed in this Pull Request:
- Allow disabling of boolean command flags (`--<flag>=false`)

### CODE REVIEW

**Comment by emclaug2** [comment]
Are there any instructions on how to run the cli locally instead of using a globally installed package?

**Comment by joebochill** [comment]
> Are there any instructions on how to run the cli locally instead of using a globally installed package?

Not at the moment. We can update the README with a section for maintainers though. Essentially, you just:
1. Clone the repo
2. cd root
3. yarn install
4. yarn link

Then you can use pxb command anywhere (recommend **not** doing it within the pxblue-cli folder)

**Comment by emclaug2** [comment]
> > Are there any instructions on how to run the cli locally instead of using a globally installed package?
> 
> Not at the moment. We can update the README with a section for maintainers though. Essentially, you just:
> 
> 1. Clone the repo
> 2. cd root
> 3. yarn install
> 4. yarn link
> 
> Then you can use pxb command anywhere (recommend **not** doing it within the pxblue-cli folder)

Awesome, thank you.  I'm going to test out generating new angular and react projects now.

**Comment by emclaug2** [comment]
When I ran `pxb-cli new angular --lint=false` I got this error: 
image

**Comment by emclaug2** [comment]
> When I ran `pxb-cli new angular --lint=false` I got this error:
> 
> image

This is because @pxblue/angular-components@^2.0.0 isn't published yet.

**Comment by emclaug2** [comment]
Similar error when making a react app, but different dependency: 

image

**Comment by joebochill** [comment]
@emclaug2 you are correct. This was mentioned in the last PR that introduced the version locks (https://github.com/pxblue/pxblue-cli/pull/30) but I didn't re-mention it here:

>Note: It will not work as-is until the new component and theme packages are available (in testing, you can swap those hardcoded numbers for @beta).

**Comment by emclaug2** [comment]
Whenever I run `pxb new angular --lint=false` I see this:

image

**Comment by emclaug2** [comment]
And whenever I try to run `yarn start` the es5 configuration doesn't exist.

**Comment by emclaug2** [comment]
React worked with no issues :)

**Comment by jeffvg** [comment]
> And whenever I try to run `yarn start` in the generated project the es5 configuration doesn't exist.

I second that, same here

**Comment by joebochill** [comment]
@emclaug2 @jeffvg This is because the Angular 10 CLI was published a few days ago...when it creates a new project, the format is different. My PR #32 has a fix for that if you look at that one first.

**Comment by joebochill** [comment]
Changing the merge target of this so that it can be bundled with #32

**Pull request merged**
