### PR TITLE
Publish 1.0.4

### PR DESCRIPTION
**Pull request by joebochill**
#### Changes proposed in this Pull Request:
- Move angular themes to body instead of app-root
- Ensure we don't include any browser support stuff for IE < 11

Published for verification at: @pxblue/cli@1.0.4
```
npx -p @pxblue/cli pxb new
```

### CODE REVIEW

**Comment by huayunh** [comment]
error Linking assets failed？

**Comment by joebochill** [comment]
RN is still causing issues in CircleCI as discussed last week. It works locally:
image

**Comment by joebochill** [comment]
I switched the CircleCI test to build a sample using the Expo CLI instead of RNC until this issue goes away. RN released a new version last month that may also have something to do with it (but doesn't explain why everything works locally).

**Comment by jeffvg** [comment]
Just saw this running new react project from dev.

Created skeleton React project in 313.654 seconds
- Installing PX Blue React Dependencies...Error: Command failed: cd ./newrect && yarn add @material-ui/core@^4.0.0 @material-ui/icons@^4.0.0 @pxblue/react-themes@^5.0.0 @pxblue/react-components@^4.0.0 @pxblue/icons-mui@^2.0.0 @pxblue/colors@^3.0.0 react-app-polyfill typeface-open-sans
warning @material-ui/core > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
error Couldn't find any versions for "@pxblue/icons-mui" that matches "2.0.0"

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

**Comment by jeffvg** [comment]
should react be pulling @pxblue/icons-mui 2.1.1

**Comment by joebochill** [comment]
@jeffvg I think you may have hit a hiccup in npm... `@^2.0.0` will pick up 2.1.1. I just ran the command from dev and it worked...you may want to just try running it again.

**Comment by jeffvg** [comment]
> @jeffvg I think you may have hit a hiccup in npm... `@^2.0.0` will pick up 2.1.1. I just ran the command from dev and it worked...you may want to just try running it again.

Not sure what's going on...getting this for react native now....
error Couldn't find any versions for "@pxblue/react-native-components" that matches "3.0.0"

**Comment by joebochill** [comment]
> Not sure what's going on...getting this for react native now....
> error Couldn't find any versions for "@pxblue/react-native-components" that matches "3.0.0"

What version of yarn do you have? Maybe you need to clear your yarn cache.

**Comment by joebochill** [comment]
image

**Comment by jeffvg** [comment]
> > Not sure what's going on...getting this for react native now....
> > error Couldn't find any versions for "@pxblue/react-native-components" that matches "3.0.0"
> 
> What version of yarn do you have? Maybe you need to clear your yarn cache.

Third time was a charm and worked....

**Pull request merged**
