### PR TITLE
Feature/2502 rebrand blui

### PR DESCRIPTION
**Pull request by ektasawant**
Fixes 2502 .

#### Changes proposed in this Pull Request:
- Rebrand blui

#### Screenshots:

Screenshot 2021-12-15 at 4 46 37 PM

Screenshot 2021-12-15 at 4 46 58 PM

#### To Test:
-

### CODE REVIEW

**Comment by emclaug2** [comment]
I fixed an issue with the angular templates; they now use the BLUI theme.  Overall this is looking really good.

- Angular looks good, no issues.
- Ionic project created but I couldn't run it on my mac; probably an environment-related issue.
-  React generates projects with linting errors when using typescripting; fixed here: https://github.com/pxblue/react-cli-templates/tree/feature/lint-files
- RN worked without any issues here.

**Comment by emclaug2** [comment]
I manually published a beta package to help test.

**Review by emclaug2 — APPROVED** [review]

**Comment by emclaug2** [comment]
The ionic error exists in the current version of the @pxblue/cli; I think this can be ignored for now.  If we actually do drop ionic support in the future, I wouldn't worry about it.

**Comment by emclaug2** [comment]
Issues logged below:

ionic: https://github.com/pxblue/pxblue-cli/issues/111
react-templates: https://github.com/pxblue/react-cli-templates/issues/40

**Review by emclaug2 — APPROVED** [review]

**Comment by ektasawant** [comment]
> I fixed an issue with the angular templates; they now use the BLUI theme. Overall this is looking really good.
> 
> * Angular looks good, no issues.
> * Ionic project created but I couldn't run it on my mac; probably an environment-related issue.  Windows ran into an issue 2x:
>   image
> * React generates projects with linting errors when using typescript.  Not an issue with your PR; this issue exists in the PXB CLI & is fixed here: https://github.com/pxblue/react-cli-templates/tree/feature/lint-files
> * RN worked without any issues .

Thanks Evan !!!

**Comment by ektasawant** [comment]
Hi @emclaug2 , for React I am getting following error(different than above screenshot),  currently I am using node v14.17.5. Will it be fix with https://github.com/pxblue/react-cli-templates/tree/feature/lint-files ?
Screenshot 2021-12-16 at 11 42 43 AM

**Comment by emclaug2** [comment]
@ektasawant  This is the linting error that is fixed in that feature branch mentioned: 

Screen Shot 2021-12-16 at 8 14 49 AM

**Comment by daileytj** [comment]
Expo projects won't build until we make the org name change because the cli-helpers are being pulled directly from `https://github.com/brightlayer-ui/cli-helpers/` so we'll need to be sure to test that after the org name change.

**Comment by daileytj** [comment]
I'm not sure what's happening here and I've tried multiple variations of the `--template=templateName@x.x.x`.  to get the RN beta templates to work but no luck. I've never used this before and generally test with the local file path for this kind of stuff. Might be worth investigating though. Looks like the template name is being pulled from github instead of npm. Perhaps I just don't understand how the --template feature works ¯\_(ツ)_/¯ 

Some of the commands I attempted were
`blui new --template=@brightlayer-ui/react-native-template-authentication-typescript@2.0.0-beta.0 --beta`
`blui new --template=@brightlayer-ui/react-native-template-authentication-typescript@2.0.0-beta.0`
`blui new --template=@brightlayer-ui/react-native-template-authentication-typescript --beta`

these are the results...
Screen Shot 2021-12-16 at 10 28 06 AM
Screen Shot 2021-12-16 at 10 28 13 AM

**Comment by jeffvg** [comment]
> npx -p @brightlayer-ui/cli@beta blui new

this worked for me...

npx -p @brightlayer-ui/cli@beta blui new react-native --template file:/Users/e0458886/proj/react-native-cli-templates/blank

**Comment by emclaug2** [comment]
@daileytj  

`npx -p @brightlayer-ui/cli@beta blui new --template=authentication@beta`

Template has to be 'blank' 'routing' or 'authentication' to work; tested locally!

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
